-- MySQL Script generated by MySQL Workbench
-- Mon Nov 17 13:42:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema logistica_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logistica_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logistica_db` DEFAULT CHARACTER SET utf8 ;
USE `logistica_db` ;

-- -----------------------------------------------------
-- Table `logistica_db`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistica_db`.`clientes` (
  `id_cliente` INT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `sobrenome_cliente` VARCHAR(100) NOT NULL,
  `cpf_cliente` CHAR(11) NOT NULL,
  `telefone_cliente` VARCHAR(20) NOT NULL,
  `email_cliente` VARCHAR(150) NOT NULL,
  `logradouro_cliente` VARCHAR(100) NOT NULL,
  `rua_cliente` VARCHAR(100) NOT NULL,
  `numero_cliente` VARCHAR(10) NOT NULL,
  `bairro_cliente` VARCHAR(100) NOT NULL,
  `cidade_cliente` VARCHAR(100) NOT NULL,
  `estado_cliente` VARCHAR(2) NOT NULL,
  `cep_cliente` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_cliente_UNIQUE` (`cpf_cliente` ASC) VISIBLE,
  UNIQUE INDEX `email_cliente_UNIQUE` (`email_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistica_db`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistica_db`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `data_pedido` DATE NOT NULL,
  `tipoEntrega_pedido` VARCHAR(100) NOT NULL,
  `pesoKg_pedido` DECIMAL(10,2) NOT NULL,
  `distanciaKm_pedido` DECIMAL(10,2) NOT NULL,
  `valorBaseKg_pedido` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedidos_Clientes_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `logistica_db`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistica_db`.`entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistica_db`.`entregas` (
  `id_entrega` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `valorDistancia_entrega` DECIMAL(10,2) NOT NULL,
  `valorPeso_entrega` DECIMAL(10,2) NOT NULL,
  `acrescimo_entrega` DECIMAL(10,2) NOT NULL,
  `desconto_entrega` DECIMAL(10,2) NOT NULL,
  `taxaAdicional_entrega` DECIMAL(10,2) NOT NULL,
  `valorFinal_entrega` DECIMAL(10,2) NOT NULL,
  `status_entrega` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_entrega`),
  INDEX `fk_entregas_pedidos1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_entregas_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `logistica_db`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;